SRC_DIR := ./src/cpp
BUILD_DIR := ./src
TARGET := cpp.js

STD_FLAG := -std=c++11

WASM_FLAG := WASM=1

EXPORTED_FUNCTIONS := '["_plusOne"]'
EXPORTED_FUNCTIONS_FLAG := EXPORTED_FUNCTIONS=${EXPORTED_FUNCTIONS}
EXPORTED_RUNTIME_METHODS_FLAG := EXPORTED_RUNTIME_METHODS='["ccall","cwrap"]'

all:
	em++ ${SRC_DIR}/main.cpp \
	${STD_FLAG} \
	-s ${WASM_FLAG} \
	-s ${EXPORTED_FUNCTIONS_FLAG} \
	-s ${EXPORTED_RUNTIME_METHODS_FLAG} \
	-O3 \
	-o ${BUILD_DIR}/${TARGET}
